[
  {
    "text": "prescription report",
    "context": "medical report, diagnosis",
    "selected_document_class_details": [
      { "document_class": "Eyewear Prescription", "node_id": "C3166217-0" },
      { "document_class": "Eyewear Prescription", "node_id": "C3173814-1" },
      { "document_class": "Medical Equipment or Product Note", "node_id": "C4554360-1" },
      { "document_class": "Medical Equipment or Product Note", "node_id": "C4554361-0" },
      { "document_class": "Ophthalmology Note", "node_id": "C1369674-1" },
      { "document_class": "Optometry Note", "node_id": "C1369677-1" },
      { "document_class": "Prescription", "node_id": "C1521941-0" },
      { "document_class": "Prescription for Medical Equipment or Product", "node_id": "C2736248-1" },
      { "document_class": "Prescription for Medical Equipment or Product", "node_id": "C2736249-0" },
      { "document_class": "Medication Prescription", "node_id": "C0033081-0" },
      { "document_class": "Medication Prescription", "node_id": "C2736256-1" },
      { "document_class": "Portable Medical Order Form", "node_id": "C4760335-0" },
      { "document_class": "Pharmacology Note", "node_id": "C1369687-1" },
      { "document_class": "Portable Medical Order Form", "node_id": "C4760335-2" },
      { "document_class": "Prescription List", "node_id": "C3533331-0" },
      { "document_class": "Prescription for Diagnostic or Specialist Care", "node_id": "C2736255-0" },
      { "document_class": "Rehabilitation Prescription", "node_id": "C2736253-0" },
      { "document_class": "Report", "node_id": "C0684224-0" },
      { "document_class": "Form", "node_id": "C0376315-0" },
      { "document_class": "Form", "node_id": "C4255237-1" },
      { "document_class": "Report", "node_id": "C4255046-1" },
      { "document_class": "Treatment Plan", "node_id": "C0599880-0" },
      { "document_class": "List Document", "node_id": "C0745732-0" },
      { "document_class": "Prescription List", "node_id": "C2741652-1" },
      { "document_class": "Action Plan", "node_id": "C3847845-0" },
      { "document_class": "Notes", "node_id": "C1316572-1" },
      { "document_class": "Notes", "node_id": "C1317574-0" },
      { "document_class": "Nurse Discharge Instructions", "node_id": "C4071074-1" },
      { "document_class": "Nurse Practitioner Discharge Instructions", "node_id": "C4071073-1" },
      { "document_class": "Obstetrics Discharge Instructions", "node_id": "C4696552-1" },
      { "document_class": "Obstetrics and Gynecology Discharge Instructions", "node_id": "C4070871-1" },
      { "document_class": "Oncology Discharge Instructions", "node_id": "C4071070-1" },
      { "document_class": "Orders Placed", "node_id": "C4034376-0" },
      { "document_class": "Outpatient Discharge Instructions", "node_id": "C5885999-1" },
      { "document_class": "Palliative Care Discharge Instructions", "node_id": "C4070966-1" },
      { "document_class": "Pediatric Discharge Instructions", "node_id": "C4070967-1" },
      { "document_class": "Pharmacology Discharge Instructions", "node_id": "C4070962-1" },
      { "document_class": "Physician Discharge Instructions", "node_id": "C4285476-1" },
      { "document_class": "Prescription List", "node_id": "C2741652-2" },
      { "document_class": "Prescription List", "node_id": "C3533331-1" },
      { "document_class": "Respiratory Therapy Discharge Instructions", "node_id": "C4070965-1" },
      { "document_class": "Urgent Care Center Discharge Instructions", "node_id": "C4297091-1" },
      { "document_class": "Care Note", "node_id": "C3871191-0" },
      { "document_class": "Summary Note", "node_id": "C3262543-1" },
      { "document_class": "Summary Note", "node_id": "C5887251-0" },
      { "document_class": "Care Management Note", "node_id": "C4760026-0" },
      { "document_class": "Care Management Note", "node_id": "C4760027-1" },
      { "document_class": "Evaluation Note", "node_id": "C2360544-1" },
      { "document_class": "Evaluation Note", "node_id": "C2360545-0" },
      { "document_class": "Evaluation and Management Note", "node_id": "C1317348-0" },
      { "document_class": "Evaluation and Management of a Specific Problem Document", "node_id": "C5212822-0" },
      { "document_class": "Evaluation and Plan Note", "node_id": "C2360542-1" },
      { "document_class": "Evaluation and Plan Note", "node_id": "C2360542-2" },
      { "document_class": "Evaluation and Plan Note", "node_id": "C2360543-0" },
      { "document_class": "Evaluation and Plan Note", "node_id": "C2360543-1" },
      { "document_class": "Medication Management Note", "node_id": "C3262524-0" },
      { "document_class": "Medication Management Note", "node_id": "C3482030-1" },
      { "document_class": "Plan of Care Note", "node_id": "C3543829-0" },
      { "document_class": "Medication Reconciliation Form", "node_id": "C4255194-0" },
      { "document_class": "Community Health Care Report", "node_id": "C4069370-1" },
      { "document_class": "Medication Reconciliation Form", "node_id": "C4255428-1" },
      { "document_class": "Medication Reconciliation Form", "node_id": "C4255194-1" },
      { "document_class": "Medication Reconciliation Form", "node_id": "C4255428-2" },
      { "document_class": "Medication Administration Flowsheet", "node_id": "C4263742-1" },
      { "document_class": "Instructions", "node_id": "C1442085-0" },
      { "document_class": "Instructions", "node_id": "C3263700-1" },
      { "document_class": "Medication Instructions", "node_id": "C4037571-1" },
      { "document_class": "Prescription for Diagnostic or Specialist Care", "node_id": "C2736254-1" },
      { "document_class": "Mandatory Reporting Form", "node_id": "C4067734-0" },
      { "document_class": "Public Health Form", "node_id": "C4071484-1" },
      { "document_class": "Case Report", "node_id": "C0085973-0" },
      { "document_class": "Complex Medical Conditions Action Plan", "node_id": "C3669163-0" },
      { "document_class": "Complex Medical Conditions Action Plan", "node_id": "C3669164-1" },
      { "document_class": "Comprehensive Plan of Care Note", "node_id": "C5776620-0" },
      { "document_class": "Infectious Disease Note", "node_id": "C1369648-1" },
      { "document_class": "Infectious Disease Plan of Care Note", "node_id": "C4265986-1" },
      { "document_class": "Multidisciplinary Comprehensive Plan of Care Note", "node_id": "C5776619-1" },
      { "document_class": "Plan of Care Note", "node_id": "C0801790-1" },
      { "document_class": "Plan of Care and Summary Note", "node_id": "C3699544-1" },
      { "document_class": "Notification", "node_id": "C5203316-0" },
      { "document_class": "Flowsheet", "node_id": "C3869813-0" },
      { "document_class": "Flowsheet", "node_id": "C4255235-1" },
      { "document_class": "Medication Administration Flowsheet", "node_id": "C4263742-0" },
      { "document_class": "Medication Administration Record", "node_id": "C4521131-0" },
      { "document_class": "Medication Administration Flowsheet", "node_id": "C4255469-2" },
      { "document_class": "Discharge Summary Note", "node_id": "C0801840-1" },
      { "document_class": "Discharge Summary Note", "node_id": "C1317307-0" },
      { "document_class": "Cardiovascular Disease Discharge Instructions", "node_id": "C4036926-1" },
      { "document_class": "Discharge Instructions", "node_id": "C3669312-1" },
      { "document_class": "Discharge Instructions", "node_id": "C4282220-0" },
      { "document_class": "Emergency Department Discharge Instructions", "node_id": "C2970125-1" },
      { "document_class": "General Medicine Discharge Instructions", "node_id": "C4071172-1" },
      { "document_class": "Geriatric Medicine Discharge Instructions", "node_id": "C4265919-1" },
      { "document_class": "Gynecology Discharge Instructions", "node_id": "C4696546-1" },
      { "document_class": "Hospital Discharge Instructions", "node_id": "C0488554-1" },
      { "document_class": "Mental Health Discharge Instructions", "node_id": "C4071173-1" },
      { "document_class": "Neonatal Perinatal Medicine Discharge Instructions", "node_id": "C4071077-1" },
      { "document_class": "Nephrology Discharge Instructions", "node_id": "C4071076-1" },
      { "document_class": "Neurology Discharge Instructions", "node_id": "C4071075-1" },
      { "document_class": "Administrative Note", "node_id": "C2360549-1" },
      { "document_class": "Administrative Note", "node_id": "C2360550-0" },
      { "document_class": "FHIR Resource Patient Medical Record", "node_id": "C5781947-0" },
      { "document_class": "Portable Medical Order Form", "node_id": "C4760334-3" },
      { "document_class": "Portable Medical Order Form", "node_id": "C4760334-1" },
      { "document_class": "Ophthalmology Diagnostic Study Note", "node_id": "C4070972-1" },
      { "document_class": "Optometry Diagnostic Study Note", "node_id": "C4070971-1" },
      { "document_class": "Registry Report", "node_id": "C3871172-0" },
      { "document_class": "Summary Registry Report", "node_id": "C3833440-2" },
      { "document_class": "Summary Registry Report", "node_id": "C3833461-1" },
      { "document_class": "Ophthalmology Evaluation Note", "node_id": "C5426428-1" },
      { "document_class": "Outpatient Instructions", "node_id": "C5886000-1" },
      { "document_class": "Physical Medicine and Rehabilitation Note", "node_id": "C1369689-1" },
      { "document_class": "Rehabilitation Prescription", "node_id": "C2736252-1" },
      { "document_class": "Prescription Request", "node_id": "C3656021-0" },
      { "document_class": "Referral Note", "node_id": "C2734725-0" },
      { "document_class": "Referral Note", "node_id": "C2735498-1" },
      { "document_class": "Request Document", "node_id": "C1272683-0" },
      { "document_class": "Diagnostic Study Note", "node_id": "C3261189-0" },
      { "document_class": "Diagnostic Study Note", "node_id": "C3482028-1" },
      { "document_class": "Prescription for Durable Medical Equipment Attachment", "node_id": "C2359978-0" }
    ]
  }
]
