resources:
  repositories:
    - repository: modn
      type: git
      name: Mayo Open Developer Network/modn-deployment-templates

trigger:
  branches:
    include:
      - main
      - aif/*
  paths:
    include:
      - config/*

pool:
  vmImage: ubuntu-latest

steps:
  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.dev"
      pipelineVariable: "ENV_DEV"

  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.test"
      pipelineVariable: "ENV_TEST"

  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.stage"
      pipelineVariable: "ENV_STAGE"

  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.prod"
      pipelineVariable: "ENV_PROD"

  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.secrets.dev"
      pipelineVariable: "SECRETS_DEV"

  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.secrets.test"
      pipelineVariable: "SECRETS_TEST"

  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.secrets.stage"
      pipelineVariable: "SECRETS_STAGE"

  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.secrets.prod"
      pipelineVariable: "SECRETS_PROD"

  - template: dotenv/dotenv-to-pipeline-variable-for-cloudrun.yml@modn
    parameters:
      filePath: "config/.env.aif"
      pipelineVariable: "ENV_AIF"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "config"
      artifact: "config"
      publishLocation: "pipeline"

  - task: ImportExportVariables@1
    inputs:
      action: "Export"
